# Generated by Django 3.0.5 on 2020-04-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zgloszenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(max_length=250)),
                ('miejsce', models.CharField(max_length=50)),
                ('imie', models.CharField(max_length=40)),
                ('nazwisko', models.CharField(max_length=40)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
